# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0002_auto_20160426_2002'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poll',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='poll',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='poll',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'question')]),
        ),
    ]
