# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptest', '0004_auto_20160428_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['choice']},
        ),
    ]
